name: flow

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - pillow
  - matplotlib
  - hydra-core
  - ipykernel
  - ipywidgets
  - ruff
  - black
  - pytest
  - pre-commit
  - htop
  - protobuf

  - pip:
    - torch>=2.3
    - torchvision>=0.18
    - tensorflow-macos>=2.16
    - waymo-open-dataset-tf-2-12-0
