# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waymo_open_dataset/protos/end_to_end_driving_metrics.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:waymo_open_dataset/protos/end_to_end_driving_metrics.proto\x12\x12waymo.open_dataset\"\xba\x03\n\x0b\x45\x32\x45\x44Metrics\x12\x18\n\raverage_score\x18\x01 \x01(\x02:\x01\x30\x12\x1d\n\x12\x63onstruction_score\x18\x02 \x01(\x02:\x01\x30\x12\x1d\n\x12intersection_score\x18\x03 \x01(\x02:\x01\x30\x12\x1b\n\x10pedestrian_score\x18\x04 \x01(\x02:\x01\x30\x12\x18\n\rcyclist_score\x18\x05 \x01(\x02:\x01\x30\x12$\n\x19multi_lane_maneuver_score\x18\x06 \x01(\x02:\x01\x30\x12%\n\x1asingle_lane_maneuver_score\x18\x07 \x01(\x02:\x01\x30\x12\x17\n\x0c\x63ut_in_score\x18\x08 \x01(\x02:\x01\x30\x12&\n\x1b\x66oreign_object_debris_score\x18\t \x01(\x02:\x01\x30\x12 \n\x15special_vehicle_score\x18\n \x01(\x02:\x01\x30\x12\x1a\n\x0fspotlight_score\x18\x0b \x01(\x02:\x01\x30\x12\x17\n\x0cothers_score\x18\x0c \x01(\x02:\x01\x30\x12\x1b\n\x10\x61\x64\x65_at_three_sec\x18\r \x01(\x02:\x01\x30\x12\x1a\n\x0f\x61\x64\x65_at_five_sec\x18\x0e \x01(\x02:\x01\x30')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'waymo_open_dataset.protos.end_to_end_driving_metrics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_E2EDMETRICS']._serialized_start=83
  _globals['_E2EDMETRICS']._serialized_end=525
# @@protoc_insertion_point(module_scope)
